[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
move_pool = "AmFDUdCyJM8FAo6RrHyfQWb47bR9Ero8Px8u7KeQbhU8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
upgradeable = true

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata_program.so"
